#!/usr/bin/env -S conda env update -f
# conda env for instalily
name: instalily_env
dependencies:
  - python=3.11
  - pip
  - pip:
      - black
      - pylint
      - python_dotenv
      - selenium
      - requests
      - pandas
      - undetected-chromedriver
      - pyyaml
      - lxml
      - tqdm
      - py2neo
      - langchain
      - openai
      - langchain-community
      - neo4j
      - tiktoken
      - langchain-openai
      - fastapi
      - uvicorn
